services:
  ui:
    build:
      context: ./lame-dimension-dialogue-tool-react
      args:
        REACT_APP_API_DOMAIN: $LD_API_DOMAIN
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_DOMAIN=http://api:8080/
  api:
    build: ./lame-dimension-dialogue-tool-api
    ports:
      - "8080:8080"
    environment:
      - JWT_SIGNING_KEY=$JWT_SIGNING_KEY
      - LD_DB_URL=mongodb://datalayer/lame-dimension-db?retryWrites=true
  datalayer:
    image: "mongo"
    restart: always
