version: "3"
services:
  ui:
    build:
      context: ./lame-dimension-dialogue-tool-react
      args:
        REACT_APP_API_DOMAIN: $LD_API_DOMAIN
    ports:
      - "9990:80"
    environment:
      - REACT_APP_API_DOMAIN=http://api:9900/
  api:
    build: ./lame-dimension-dialogue-tool-api
    ports:
      - "9900:8080"
    environment:
      - JWT_SIGNING_KEY=$JWT_SIGNING_KEY
      - LD_DB_URL=mongodb://10.0.0.244/lame-dimension-db?retryWrites=true
