import DataTable from './DataTable';
import moveTemplate from './templates/move.template';

// TODO Add more templates for each category, or make these customizable through the ui.
export default {
    characters: {
        title: {
            en: 'Characters',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'characterName',
        template: moveTemplate,
    },
    enemies: {
        title: {
            en: 'Enemies',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'characterName',
        template: moveTemplate,
    },
    moves: {
        title: {
            en: 'Moves',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'name',
        template: moveTemplate,
    },
    weapons: {
        title: {
            en: 'Weapons',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'name',
        template: moveTemplate,
    },
    armors: {
        title: {
            en: 'Armors',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'name',
        template: moveTemplate,
    },
    items: {
        title: {
            en: 'Items',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'name',
        template: moveTemplate,
    },
    keyItems: {
        title: {
            en: 'Key-Items',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'name',
        template: moveTemplate,
    },
    locations: {
        title: {
            en: 'Locations',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'section',
        template: moveTemplate,
    },
    ui: {
        title: {
            en: 'UI',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'display',
        template: moveTemplate,
    },
    other: {
        title: {
            en: 'Other',
            es: '',
            jp: '',
            fr: '',
            br: '',
            ch: '',
            de: '',
            ru: '',
        },
        nameField: 'display',
        template: moveTemplate,
    },
};
